# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "https://FoyCR.github.io"

[_.globalMeta]
title = "Foyland"
description = "Blog and Gtihub portfolio by Roy Barrantes (AKA Foy)"
longDescription = "Desarrallador y líder técnico, con experiencia en tecnologías Microsoft desde los tiempos del VB6 y el asp clásico hasta el .Net Core, pasando por COM+, javascript, angularjs, Ionic, xaml, cordova, MVC, Web Api, Sql Server, Oracle... . Ávido lector, apasionado programador."
cardImage = "https://FoyCR.github.io/Foy.webp"
keywords = ["web development", ".Net developer", "technology","Databases"]

[_.blogMeta]
title = "Foyland Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "https://FoyCR.github.io/Foy.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Foyland Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://FoyCR.github.io/Foy.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Foyland 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://FoyCR.github.io/Foy.webp"

[_.hero]
title = "Foyland"
subtitle = "Devenires y vicisitudes en el mundillo de la programación.<br />Y otras foysadas..."
image = "https://FoyCR.github.io/Foy.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Roy Barrantes (Foy)"
githubProfile = "https://github.com/FoyCR"
twitterProfile = "https://twitter.com"
linkedinProfile = "https://www.linkedin.com/in/barrantesroy/"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"